version: '3.8'
services:
  db:
    container_name: db_sql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kai_For(DB_SQL)
      MYSQL_DATABASE: Trade_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: Kai_For(DB_SQL)
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db


